#! /usr/bin/python
##################################
#
# uniPRCsim
# Copyright (C) Louisiana State University, Health Sciences Center
# Written by 2011-2013 Ruben Tikidji-Hamburyan <rth@nisms.krinc.ru>
#               
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, GOOD TITLE or
# NON INFRINGEMENT.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
###################################

import sys, os, zipfile,stat

#nonlocal BASEDIR
#global BASEDIR
BASEDIR="/home/rth/projects/uniPRCsim/"

GUI = True
for arg in sys.argv[1:]:
	if arg == "--nogui": GUI=False
	if arg == "--help" or arg == "-h" or arg == "/help" or arg == "/h" or arg == "?":
		sys.stderr.write("%s [--nogui] [file.pxm]\n\n"%sys.argv[0])
		sys.stderr.write("%s --version\n"%sys.argv[0])
		sys.stderr.write("%s --update updatefile\n\n"%sys.argv[0])
		sys.exit(0)
	if arg == "--version" or arg =="-v" or arg == "/version" or arg == "/v" or arg == "/V":
		import uniprcsimversion
		sys.stderr.write("\n\n" + uniprcsimversion.getlongversion() +"\n\n")
		sys.exit(0)
	if arg == "--install" or arg == "-i" or arg == "/install" or arg == "/i" or arg == "-I" or arg =="/I":
		if not os.path.isdir(os.getenv("HOME")+"/.local"):
			os.mkdir(os.getenv("HOME")+"/.local")
		if not os.path.isdir(os.getenv("HOME")+"/.local/lib"):
			os.mkdir(os.getenv("HOME")+"/.local/lib")
		BDIR=os.getenv("HOME")+"/.local/lib/uniPRCsim"
		os.mkdir(BDIR)
		dsfile = open(BDIR+"/uniPRCsim","w")
		srfile = open(sys.argv[0],"r")
		for line in srfile.readlines():
			if line[:len("BASEDIR=")] == "BASEDIR=":
				dsfile.write("BASEDIR=\"%s/\"\n"%BDIR)
			else:
				dsfile.write(line)
		dsfile.close()
		srfile.close()
		os.chmod(BDIR+"/uniPRCsim",stat.S_IXUSR|stat.S_IRUSR|stat.S_IWUSR)
		os.system(BDIR+"/uniPRCsim -u %s"%sys.argv[-1])
		if os.path.isdir(os.getenv("HOME")+"/bin"):
			os.symlink(BDIR+"/uniPRCsim",os.getenv("HOME")+"/bin/uniPRCsim")
		else:
			os.symlink(BDIR+"/uniPRCsim",os.getenv("HOME")+"/uniPRCsim")
		sys.exit(0)
	if arg == "--update" or arg == "-u" or arg == "/update" or arg == "/u" or arg == "-U" or arg =="/U":
			file = zipfile.ZipFile( sys.argv[-1],"r")
			for name in file.namelist():
				sys.stderr.write("uniPRCsim: update %s file ... "%name)
				fd = open(BASEDIR+"/"+name,"w")
				fd.write(file.read(name) )
				fd.close()
				sys.stderr.write("ok\n")
			sys.exit(0)

if not os.path.isdir(BASEDIR):
	sys.stderr.write("INSTALL ME\n\n")
	sys.exit(1)

sys.path.append(BASEDIR)

if GUI:
	from PyQt4 import QtGui, QtCore
	import glmainwnd
	app = QtGui.QApplication(sys.argv)
	main = glmainwnd.glmainwnd()
	if len(sys.argv) > 1:
		main.model.readfile(QtCore.QString(sys.argv[-1]))
	main.show()
	sys.exit(app.exec_())
else:
	import engine
	import modelparcer as mp
	from xml.sax import make_parser
	import threading as td

	if len(sys.argv) == 1:
		print "USAGE: %s [OPTIONS] modelfile.pxm" % sys.argv[0]
		sys.exit(1)
	egn = engine.engine(filename=sys.argv[-1])
	egn.run()
	print "ok!"
	
