#! /usr/bin/python
import sys, os
import uniprcsimversion
import zipfile

#nonlocal BASEDIR
#global BASEDIR
BASEDIR="/home/rth/projects/uniPRCsim/"


if not BASEDIR:
	sys.stderr.write("INTALL ME\n\n")
	sys.exit(1)

sys.path.append(BASEDIR)
GUI = True
for arg in sys.argv[1:]:
	if arg == "--nogui": GUI=False
	if arg == "--help" or arg == "-h" or arg == "/help" or arg == "/h" or arg == "?":
		sys.stderr.write("%s [--nogui] [file.pxm]\n\n"%sys.arg[0])
		sys.stderr.write("%s --version\n"%sys.arg[0])
		sys.stderr.write("%s --update updatefile\n\n"%sys.arg[0])
		sys.exit(0)
	if arg == "--version" or arg =="-v" or arg == "/version" or arg == "/v" or arg == "/V":
		sys.stderr.write("\n\n" + uniprcsimversion.getlongversion() +"\n\n")
		sys.exit(0)
	if arg == "--update" or arg == "-u" or arg == "/update" or arg == "/u" or arg == "-U" or arg =="/U":
			file = zipfile.ZipFile( sys.argv[-1],"r")
			for name in file.namelist():
				sys.stderr.write("uniPRCsim: update %s file ... "%name)
				fd = open(BASEDIR+name,"w")
				fd.write(file.read(name) )
				fd.close()
				sys.stderr.write("ok\n")
			sys.exit(0)
		
if GUI:
	from PyQt4 import QtGui, QtCore
	import glmainwnd
	app = QtGui.QApplication(sys.argv)
	main = glmainwnd.glmainwnd()
	if len(sys.argv) > 1:
		main.model.readfile(QtCore.QString(sys.argv[-1]))
	main.show()
	sys.exit(app.exec_())
else:
	import engine
	import modelparcer as mp
	from xml.sax import make_parser
	import threading as td

	if len(sys.argv) == 1:
		print "USAGE: %s [OPTIONS] modelfile.pxm" % sys.argv[0]
		sys.exit(1)
	egn = engine.engine(filename=sys.argv[-1])
	egn.run()
	print "ok!"
	
